# config/routes.yaml
app_home:
    path: /
    controller: App\Controller\HomeController::index

controllers:
    resource: '../src/Controller/'
    type: attribute    # Use 'annotation' for @Route or 'attribute' for #[Route]